// Run this once to populate degrees in your local MongoDB instance
// node backend/seedDegrees.js

const mongoose = require('mongoose')
const dotenv = require('dotenv')
dotenv.config()

const Degree = require('./models/Degree')
const logger = require('./utils/logger')

const degrees = [
  {
    name: 'BS Computer Science',
    shortName: 'BSCS',
    field: 'Technology',
    description:
      'Study algorithms, software engineering, AI, databases and systems.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Computer', 'Physics'],
    requiredStream: ['science', 'technology'],
    minGPA: 2.5,
    universities: [
      {
        name: 'FAST-NUCES',
        location: 'Lahore/Karachi/Islamabad',
        ranking: 1,
        feePerYear: 'PKR 180,000',
        hasScholarship: true,
        admissionTest: 'NU Entry Test',
        website: 'nu.edu.pk',
      },
      {
        name: 'NUST',
        location: 'Islamabad',
        ranking: 2,
        feePerYear: 'PKR 200,000',
        hasScholarship: true,
        admissionTest: 'NET',
        website: 'nust.edu.pk',
      },
      {
        name: 'LUMS',
        location: 'Lahore',
        ranking: 3,
        feePerYear: 'PKR 600,000',
        hasScholarship: true,
        admissionTest: 'SAT/LCAT',
        website: 'lums.edu.pk',
      },
      {
        name: 'UET Lahore',
        location: 'Lahore',
        ranking: 4,
        feePerYear: 'PKR 80,000',
        hasScholarship: true,
        admissionTest: 'ECAT',
        website: 'uet.edu.pk',
      },
      {
        name: 'COMSATS',
        location: 'Multiple Cities',
        ranking: 5,
        feePerYear: 'PKR 120,000',
        hasScholarship: true,
        admissionTest: 'Entry Test',
        website: 'comsats.edu.pk',
      },
    ],
    careerOutcomes: [
      'Software Engineer',
      'Web Developer',
      'Mobile App Developer',
      'AI Engineer',
      'Data Scientist',
      'System Analyst',
      'DevOps Engineer',
    ],
    expectedSalary: 'PKR 80,000 - 300,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Technology', 'Engineering'],
    idealActivities: ['Problem Solving', 'Research', 'Building Things'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 85,
    averageRating: 4.5,
  },
  {
    name: 'BS Artificial Intelligence',
    shortName: 'BSAI',
    field: 'Technology',
    description:
      'Deep learning, neural networks, computer vision, NLP and intelligent systems.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Computer', 'Statistics'],
    requiredStream: ['science', 'technology'],
    minGPA: 3.0,
    universities: [
      {
        name: 'FAST-NUCES',
        location: 'Lahore/Islamabad',
        ranking: 1,
        feePerYear: 'PKR 190,000',
        hasScholarship: true,
        admissionTest: 'NU Entry Test',
        website: 'nu.edu.pk',
      },
      {
        name: 'NUST',
        location: 'Islamabad',
        ranking: 2,
        feePerYear: 'PKR 210,000',
        hasScholarship: true,
        admissionTest: 'NET',
        website: 'nust.edu.pk',
      },
      {
        name: 'ITU',
        location: 'Lahore',
        ranking: 3,
        feePerYear: 'PKR 150,000',
        hasScholarship: true,
        admissionTest: 'ITU Test',
        website: 'itu.edu.pk',
      },
    ],
    careerOutcomes: [
      'AI Engineer',
      'Machine Learning Engineer',
      'Data Scientist',
      'Research Scientist',
      'NLP Engineer',
    ],
    expectedSalary: 'PKR 120,000 - 400,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Technology', 'Research'],
    idealActivities: ['Problem Solving', 'Research', 'Data Analysis'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 80,
    averageRating: 4.6,
  },
  {
    name: 'BS Software Engineering',
    shortName: 'BSSE',
    field: 'Technology',
    description:
      'Software design, development, testing and project management.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Computer'],
    requiredStream: ['science', 'technology'],
    minGPA: 2.5,
    universities: [
      {
        name: 'UET Lahore',
        location: 'Lahore',
        ranking: 1,
        feePerYear: 'PKR 75,000',
        hasScholarship: true,
        admissionTest: 'ECAT',
        website: 'uet.edu.pk',
      },
      {
        name: 'NUST',
        location: 'Islamabad',
        ranking: 2,
        feePerYear: 'PKR 195,000',
        hasScholarship: true,
        admissionTest: 'NET',
        website: 'nust.edu.pk',
      },
      {
        name: 'COMSATS',
        location: 'Multiple Cities',
        ranking: 3,
        feePerYear: 'PKR 115,000',
        hasScholarship: false,
        admissionTest: 'Entry Test',
        website: 'comsats.edu.pk',
      },
      {
        name: 'Virtual University',
        location: 'Online',
        ranking: 4,
        feePerYear: 'PKR 30,000',
        hasScholarship: false,
        admissionTest: 'None',
        website: 'vu.edu.pk',
      },
    ],
    careerOutcomes: [
      'Software Engineer',
      'Full Stack Developer',
      'QA Engineer',
      'Project Manager',
      'Technical Lead',
    ],
    expectedSalary: 'PKR 70,000 - 250,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Technology', 'Engineering'],
    idealActivities: ['Problem Solving', 'Building Things', 'Team Work'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'practical',
    successRate: 83,
    averageRating: 4.3,
  },
  {
    name: 'MBBS',
    shortName: 'MBBS',
    field: 'Medical',
    description:
      'Bachelor of Medicine and Surgery. Become a licensed medical doctor.',
    duration: '5 years',
    requiredSubjects: ['Biology', 'Chemistry', 'Physics'],
    requiredStream: ['science'],
    minGPA: 3.5,
    universities: [
      {
        name: 'King Edward Medical University',
        location: 'Lahore',
        ranking: 1,
        feePerYear: 'PKR 50,000',
        hasScholarship: true,
        admissionTest: 'MDCAT',
        website: 'kemu.edu.pk',
      },
      {
        name: 'Aga Khan University',
        location: 'Karachi',
        ranking: 2,
        feePerYear: 'PKR 800,000',
        hasScholarship: true,
        admissionTest: 'AKU Entry Test',
        website: 'aku.edu',
      },
      {
        name: 'Allama Iqbal Medical College',
        location: 'Lahore',
        ranking: 3,
        feePerYear: 'PKR 60,000',
        hasScholarship: false,
        admissionTest: 'MDCAT',
        website: 'aimc.edu.pk',
      },
      {
        name: 'Rawalpindi Medical University',
        location: 'Rawalpindi',
        ranking: 4,
        feePerYear: 'PKR 55,000',
        hasScholarship: true,
        admissionTest: 'MDCAT',
        website: 'rmu.edu.pk',
      },
    ],
    careerOutcomes: [
      'Doctor',
      'Surgeon',
      'Specialist Physician',
      'Medical Researcher',
      'Healthcare Administrator',
    ],
    expectedSalary: 'PKR 100,000 - 500,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Healthcare', 'Science', 'Social Work'],
    idealActivities: [
      'Helping People',
      'Research',
      'Fieldwork',
      'Communication',
    ],
    idealAnalytical: 'high',
    idealCreativity: 'low',
    workType: 'practical',
    successRate: 78,
    averageRating: 4.7,
  },
  {
    name: 'BBA (Business Administration)',
    shortName: 'BBA',
    field: 'Business',
    description:
      'Management, marketing, finance, entrepreneurship and business strategy.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Economics', 'Commerce'],
    requiredStream: ['commerce', 'science', 'arts'],
    minGPA: 2.0,
    universities: [
      {
        name: 'LUMS',
        location: 'Lahore',
        ranking: 1,
        feePerYear: 'PKR 550,000',
        hasScholarship: true,
        admissionTest: 'SAT/LCAT',
        website: 'lums.edu.pk',
      },
      {
        name: 'IBA Karachi',
        location: 'Karachi',
        ranking: 2,
        feePerYear: 'PKR 200,000',
        hasScholarship: true,
        admissionTest: 'IBA Entry Test',
        website: 'iba.edu.pk',
      },
      {
        name: 'NUST Business School',
        location: 'Islamabad',
        ranking: 3,
        feePerYear: 'PKR 180,000',
        hasScholarship: true,
        admissionTest: 'NET',
        website: 'nust.edu.pk',
      },
      {
        name: 'UCP',
        location: 'Lahore',
        ranking: 4,
        feePerYear: 'PKR 120,000',
        hasScholarship: false,
        admissionTest: 'Entry Test',
        website: 'ucp.edu.pk',
      },
    ],
    careerOutcomes: [
      'Business Manager',
      'Entrepreneur',
      'Marketing Manager',
      'Finance Analyst',
      'HR Manager',
      'Consultant',
    ],
    expectedSalary: 'PKR 60,000 - 200,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Business', 'Finance', 'Entrepreneurship'],
    idealActivities: [
      'Communication',
      'Leadership',
      'Problem Solving',
      'Team Work',
    ],
    idealAnalytical: 'medium',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 82,
    averageRating: 4.2,
  },
  {
    name: 'BS Electrical Engineering',
    shortName: 'BSEE',
    field: 'Engineering',
    description:
      'Circuits, electronics, power systems, telecommunications and control systems.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Physics', 'Computer'],
    requiredStream: ['science'],
    minGPA: 2.8,
    universities: [
      {
        name: 'UET Lahore',
        location: 'Lahore',
        ranking: 1,
        feePerYear: 'PKR 75,000',
        hasScholarship: true,
        admissionTest: 'ECAT',
        website: 'uet.edu.pk',
      },
      {
        name: 'NUST',
        location: 'Islamabad',
        ranking: 2,
        feePerYear: 'PKR 200,000',
        hasScholarship: true,
        admissionTest: 'NET',
        website: 'nust.edu.pk',
      },
      {
        name: 'NED University',
        location: 'Karachi',
        ranking: 3,
        feePerYear: 'PKR 70,000',
        hasScholarship: true,
        admissionTest: 'NED Test',
        website: 'neduet.edu.pk',
      },
      {
        name: 'COMSATS',
        location: 'Multiple Cities',
        ranking: 4,
        feePerYear: 'PKR 130,000',
        hasScholarship: false,
        admissionTest: 'Entry Test',
        website: 'comsats.edu.pk',
      },
    ],
    careerOutcomes: [
      'Electrical Engineer',
      'Power Engineer',
      'Telecom Engineer',
      'Control Systems Engineer',
      'Electronics Engineer',
    ],
    expectedSalary: 'PKR 70,000 - 250,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Engineering', 'Technology', 'Energy'],
    idealActivities: ['Problem Solving', 'Building Things', 'Research'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'practical',
    successRate: 79,
    averageRating: 4.2,
  },
  {
    name: 'BS Civil Engineering',
    shortName: 'BSCE',
    field: 'Engineering',
    description:
      'Structural design, construction, urban planning and infrastructure development.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Physics'],
    requiredStream: ['science'],
    minGPA: 2.5,
    universities: [
      {
        name: 'UET Lahore',
        location: 'Lahore',
        ranking: 1,
        feePerYear: 'PKR 70,000',
        hasScholarship: true,
        admissionTest: 'ECAT',
        website: 'uet.edu.pk',
      },
      {
        name: 'NED University',
        location: 'Karachi',
        ranking: 2,
        feePerYear: 'PKR 65,000',
        hasScholarship: true,
        admissionTest: 'NED Test',
        website: 'neduet.edu.pk',
      },
      {
        name: 'NUST',
        location: 'Islamabad',
        ranking: 3,
        feePerYear: 'PKR 195,000',
        hasScholarship: true,
        admissionTest: 'NET',
        website: 'nust.edu.pk',
      },
    ],
    careerOutcomes: [
      'Civil Engineer',
      'Structural Engineer',
      'Urban Planner',
      'Construction Manager',
      'Project Engineer',
    ],
    expectedSalary: 'PKR 60,000 - 200,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Engineering', 'Architecture', 'Environment'],
    idealActivities: ['Building Things', 'Fieldwork', 'Problem Solving'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'practical',
    successRate: 80,
    averageRating: 4.0,
  },
  {
    name: 'BS Psychology',
    shortName: 'BSPsych',
    field: 'Social Sciences',
    description:
      'Human behavior, mental health, counseling and behavioral research.',
    duration: '4 years',
    requiredSubjects: ['Biology', 'Sociology', 'English'],
    requiredStream: ['science', 'arts', 'commerce'],
    minGPA: 2.0,
    universities: [
      {
        name: 'University of Lahore',
        location: 'Lahore',
        ranking: 1,
        feePerYear: 'PKR 100,000',
        hasScholarship: false,
        admissionTest: 'Entry Test',
        website: 'uol.edu.pk',
      },
      {
        name: 'Quaid-i-Azam University',
        location: 'Islamabad',
        ranking: 2,
        feePerYear: 'PKR 40,000',
        hasScholarship: true,
        admissionTest: 'QAU Test',
        website: 'qau.edu.pk',
      },
      {
        name: 'University of Karachi',
        location: 'Karachi',
        ranking: 3,
        feePerYear: 'PKR 35,000',
        hasScholarship: false,
        admissionTest: 'Entry Test',
        website: 'uok.edu.pk',
      },
    ],
    careerOutcomes: [
      'Psychologist',
      'Counselor',
      'HR Specialist',
      'Social Worker',
      'Researcher',
      'Clinical Therapist',
    ],
    expectedSalary: 'PKR 40,000 - 120,000/month',
    jobMarket: 'moderate',
    idealInterestAreas: ['Healthcare', 'Social Work', 'Research'],
    idealActivities: ['Communication', 'Helping People', 'Research'],
    idealAnalytical: 'medium',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 84,
    averageRating: 4.0,
  },
  {
    name: 'BS Accounting & Finance',
    shortName: 'BSAF',
    field: 'Business',
    description:
      'Financial reporting, auditing, taxation, investment and corporate finance.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Accounting', 'Economics'],
    requiredStream: ['commerce', 'science'],
    minGPA: 2.0,
    universities: [
      {
        name: 'LUMS',
        location: 'Lahore',
        ranking: 1,
        feePerYear: 'PKR 540,000',
        hasScholarship: true,
        admissionTest: 'SAT/LCAT',
        website: 'lums.edu.pk',
      },
      {
        name: 'IBA Karachi',
        location: 'Karachi',
        ranking: 2,
        feePerYear: 'PKR 190,000',
        hasScholarship: true,
        admissionTest: 'IBA Test',
        website: 'iba.edu.pk',
      },
      {
        name: 'ACCA Pakistan',
        location: 'Multiple Cities',
        ranking: 3,
        feePerYear: 'PKR 80,000',
        hasScholarship: false,
        admissionTest: 'None',
        website: 'accaglobal.com',
      },
    ],
    careerOutcomes: [
      'Accountant',
      'Finance Analyst',
      'Auditor',
      'Investment Banker',
      'CFO',
      'Tax Consultant',
    ],
    expectedSalary: 'PKR 60,000 - 250,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Business', 'Finance', 'Economics'],
    idealActivities: ['Problem Solving', 'Research', 'Data Analysis'],
    idealAnalytical: 'high',
    idealCreativity: 'low',
    workType: 'theory',
    successRate: 81,
    averageRating: 4.1,
  },
  {
    name: 'BS Media & Communication',
    shortName: 'BSMC',
    field: 'Arts & Media',
    description:
      'Journalism, digital media, PR, advertising and mass communication.',
    duration: '4 years',
    requiredSubjects: ['English', 'Urdu', 'Social Studies'],
    requiredStream: ['arts', 'commerce', 'science'],
    minGPA: 2.0,
    universities: [
      {
        name: 'Punjab University',
        location: 'Lahore',
        ranking: 1,
        feePerYear: 'PKR 35,000',
        hasScholarship: false,
        admissionTest: 'Entry Test',
        website: 'pu.edu.pk',
      },
      {
        name: 'Beaconhouse National University',
        location: 'Lahore',
        ranking: 2,
        feePerYear: 'PKR 250,000',
        hasScholarship: true,
        admissionTest: 'Portfolio',
        website: 'bnu.edu.pk',
      },
      {
        name: 'Iqra University',
        location: 'Karachi/Islamabad',
        ranking: 3,
        feePerYear: 'PKR 120,000',
        hasScholarship: false,
        admissionTest: 'Entry Test',
        website: 'iqra.edu.pk',
      },
    ],
    careerOutcomes: [
      'Journalist',
      'Content Creator',
      'PR Manager',
      'Digital Marketer',
      'News Anchor',
      'Social Media Manager',
    ],
    expectedSalary: 'PKR 40,000 - 150,000/month',
    jobMarket: 'moderate',
    idealInterestAreas: ['Arts', 'Media', 'Communication', 'Technology'],
    idealActivities: ['Creativity', 'Communication', 'Fieldwork'],
    idealAnalytical: 'low',
    idealCreativity: 'high',
    workType: 'practical',
    successRate: 80,
    averageRating: 3.9,
  },
  {
    name: 'BS Architecture',
    shortName: 'BArch',
    field: 'Architecture & Design',
    description:
      'Building design, urban planning, structural aesthetics and construction.',
    duration: '5 years',
    requiredSubjects: ['Mathematics', 'Physics', 'Art'],
    requiredStream: ['science', 'arts'],
    minGPA: 2.5,
    universities: [
      {
        name: 'NCA Lahore',
        location: 'Lahore',
        ranking: 1,
        feePerYear: 'PKR 50,000',
        hasScholarship: true,
        admissionTest: 'NCA Entry Test',
        website: 'nca.edu.pk',
      },
      {
        name: 'NED University',
        location: 'Karachi',
        ranking: 2,
        feePerYear: 'PKR 65,000',
        hasScholarship: false,
        admissionTest: 'NED Test',
        website: 'neduet.edu.pk',
      },
      {
        name: 'UET Lahore',
        location: 'Lahore',
        ranking: 3,
        feePerYear: 'PKR 70,000',
        hasScholarship: true,
        admissionTest: 'ECAT',
        website: 'uet.edu.pk',
      },
    ],
    careerOutcomes: [
      'Architect',
      'Urban Planner',
      'Interior Designer',
      'Landscape Architect',
      'Construction Consultant',
    ],
    expectedSalary: 'PKR 60,000 - 200,000/month',
    jobMarket: 'moderate',
    idealInterestAreas: ['Arts', 'Engineering', 'Architecture', 'Environment'],
    idealActivities: ['Creativity', 'Building Things', 'Problem Solving'],
    idealAnalytical: 'medium',
    idealCreativity: 'high',
    workType: 'both',
    successRate: 78,
    averageRating: 4.2,
  },
  {
    name: 'LLB (Law)',
    shortName: 'LLB',
    field: 'Law',
    description:
      'Constitutional law, criminal law, corporate law and legal practice in Pakistan.',
    duration: '5 years',
    requiredSubjects: ['English', 'Pakistan Studies', 'Islamiat'],
    requiredStream: ['arts', 'commerce', 'science'],
    minGPA: 2.0,
    universities: [
      {
        name: 'University of Punjab Law College',
        location: 'Lahore',
        ranking: 1,
        feePerYear: 'PKR 30,000',
        hasScholarship: false,
        admissionTest: 'Entry Test',
        website: 'pu.edu.pk',
      },
      {
        name: 'Lahore University of Management Sciences (Law)',
        location: 'Lahore',
        ranking: 2,
        feePerYear: 'PKR 500,000',
        hasScholarship: true,
        admissionTest: 'LCAT',
        website: 'lums.edu.pk',
      },
      {
        name: 'International Islamic University',
        location: 'Islamabad',
        ranking: 3,
        feePerYear: 'PKR 40,000',
        hasScholarship: true,
        admissionTest: 'IIU Test',
        website: 'iiu.edu.pk',
      },
    ],
    careerOutcomes: [
      'Lawyer',
      'Judge',
      'Legal Advisor',
      'Corporate Counsel',
      'Public Prosecutor',
      'Legal Consultant',
    ],
    expectedSalary: 'PKR 50,000 - 300,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Law', 'Social Work', 'Politics'],
    idealActivities: [
      'Communication',
      'Research',
      'Problem Solving',
      'Helping People',
    ],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'theory',
    successRate: 77,
    averageRating: 4.0,
  },
]

const seedMode = String(process.env.SEED_MODE || 'merge').toLowerCase()

const seedDegrees = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI)
    logger.info('Seed degrees connected to MongoDB', { seedMode })

    if (seedMode === 'replace') {
      await Degree.deleteMany({})
      logger.warn('Seed replace mode cleared existing degrees')
      await Degree.insertMany(degrees)
      logger.info('Seeded degrees in replace mode', { count: degrees.length })
      return
    }

    let upserted = 0
    for (const degree of degrees) {
      await Degree.updateOne(
        { shortName: degree.shortName || degree.name },
        { $set: degree },
        { upsert: true },
      )
      upserted += 1
    }
    logger.info('Seeded degrees in merge mode', { count: upserted })
  } catch (error) {
    logger.error('Seed degrees failed', {
      error: error.message,
      stack: error.stack,
      seedMode,
    })
    process.exit(1)
  } finally {
    await mongoose.connection.close()
  }
}

seedDegrees()


